name: presentacio-equip
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Create build directory
              run: mkdir -p build

            - name: Slides in HTML
              uses: docker://marpteam/marp-cli:v1.7.0
              with:
                args: PresentacioIA-Equip.md -o build/ --html --allow-local-files
              env:
                MARP_USER: root:root